### PR TITLE
header and footer

### PR DESCRIPTION
**Pull request by Dev-Liz**

### CODE REVIEW

**Review by the-genesis — COMMENTED** [review]
First off, someone's working on the header already.

Second, the issue you're trying to solve with flex and flex-direction and all of that can be solved by just putting `text-align: center;` in the parent elements of the texts. It'll center the image and text.

For the image, you can also use `margin: auto;` after setting a width to the image. It'll center it.

**Review by the-genesis — COMMENTED** [review]
Great job, though. Your code looks clean!

**Comment by Dev-Liz** [comment]
Okay...so the idea was to centralize the texts. But I thought using flexbox would also help keep the container (not just it contents) in shape (on diff screens) without media queries🙂

**Comment by Dev-Liz** [comment]
> Great job, though. Your code looks clean!

Thank you!🙂

**Comment by the-genesis** [comment]
> Okay...so the idea was to centralize the texts. But I thought using flexbox would also help keep the container (not just it contents) in shape (on diff screens) without media queries🙂

The container would remain in shape as long as there's no rule altering it's natural state. Try it, though.
There's nothing wrong with your code.

**Comment by Dev-Liz** [comment]
Alright..so i'll remove the header and correct the footer then. Thanks

**Pull request merged**
